apiVersion: v1
kind: Pod
metadata:
  name: wget-disabled
  namespace: cainjekt-demo
  labels:
    cainjekt.io/enabled: "false"
spec:
  restartPolicy: Never
  containers:
  - name: client
    image: alpine:3.20
    command: ["sh", "-lc", "sleep 3600"]
